trigger:
- master

resources:
- repo: self

variables:
  imageRepo: mypython
  tag: '$(Build.BuildId)'

stages:
- stage: Build 
  displayName: Build
  jobs:
  - job: Build
    displayName: Build an image
    pool: 
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: build and image
      inputs:
        containerRegistry: 'Registry'
        repository: '$(imageRepo)'
        command: buildAndPush
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          latest 
    - task: PublishPipelineArtifact@1
      inputs: 
        targetPath: '$(Pipeline.Workspace)/s'
        artifact: 'Drop'
        publishLocation: 'pipeline' 

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: build
  jobs:
  - job: Deploy
    displayName: Deploy to AKS
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: '$(Pipeline.Workspace)/drop'
    
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'AKSConnection'
        nameSpace: 'default'  
        manifests: $(Pipeline.Workspace)/drop/deployment.yml           







     
