apiVersion: apps/v1
kind: Deployment
metadata:
    name: sampleapp-9
    labels:
       app: sampleapp
spec:
   replicas: 3
   selector:
      matchLabels:
         app: sampleapp
   template:
      metadata:
         name: sampleapp
         labels:
            app: sampleapp
      spec:
        containers:
        - name: sampleapp
          image: newacr95.azurecr.io/mypython:latest
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: k8-cluster
    labels:
      app: sampleapp
spec:
- ports:
  port: 80
  targetPort: 8080
  selector:
    app: sampleapp  

         

